### PR TITLE
[PM-11707] Fix search results update dynamically

### LINKED ISSUE #902: Items don’t update in search view
### Bitwarden Beta

- [ ] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Open search
2. Search for item
3. Change name, username or delete item
4. See that item doesn’t update
5. Change search
6. Item gets updated

### Expected Result

Item should get updated instantly after saving or deleting item.

### Actual Result

Item doesn’t get updated.

### Screenshots or Videos

https://github.com/user-attachments/assets/5ce4b166-9db0-41ed-89f1-538426abe54d

### Additional Context

_No response_

### Build Version

2024.8.1 (1052)

### Environment Details

Device: iPhone 12
iOS: 17.6.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

### PR DESCRIPTION
**Pull request by LRNcardozoWDF**
## 🎟️ Tracking

[PM-11707](https://bitwarden.atlassian.net/browse/PM-11707)

Fixes #902 .

## 📔 Objective

Fix a bug where editing an item from the search results list wouldn't update it in the list. The view now subscribes to the search results instead of using a static list.

For the Authenticator, instead of repeating the search we we subscribed the view to search results.

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

[PM-11707]: https://bitwarden.atlassian.net/browse/PM-11707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: AuthenticatorShared/UI/Vault/ItemList/ItemList/ItemListProcessor.swift [hunk 1]
```diff
@@ -208,9 +217,21 @@ final class ItemListProcessor: StateProcessor<ItemListState, ItemListAction, Ite
...
-            }
+        } catch {
+            services.errorReporter.log(error: error)
+        }
+    }
+
+    /// Refreshes TOTP Codes for the search results.
+    ///
+    private func refreshTOTPCodes(searchItems: [ItemListItem]) async {
+        guard case let .data(currentSections) = state.loadingState else { return }
```
Comment (fedemkr) [inline AuthenticatorShared/UI/Vault/ItemList/ItemList/ItemListProcessor.swift]: 🤔 Do you need this guard for the search items?

File: AuthenticatorShared/UI/Vault/ItemList/ItemList/ItemListProcessor.swift [hunk 2]
```diff
@@ -208,9 +217,21 @@ final class ItemListProcessor: StateProcessor<ItemListState, ItemListAction, Ite
...
+        do {
+            let refreshedItems = try await services.authenticatorItemRepository.refreshTotpCodes(on: searchItems)
+            let updatedSections = currentSections.updated(with: refreshedItems)
+            let allItems = updatedSections.flatMap(\.items)
+            searchTotpExpirationManager?.configureTOTPRefreshScheduling(for: allItems)
+            state.searchResults = updatedSections[0].items
```
Comment (fedemkr) [inline AuthenticatorShared/UI/Vault/ItemList/ItemList/ItemListProcessor.swift]: 🤔 You could use a similar approach as in [here](https://github.com/bitwarden/ios/blob/main/BitwardenShared/UI/Vault/Utilities/HasTOTPCodesSections.swift#L17) to reduce code duplication even though you can't use the same as the item objects and repository are different. However, you could try to centralize them by converting the protocol to a more generic one with additional generic protocols for the repositories; therefore you can have something like `HasTOTPCodesSection<ItemListItem>` conformance here and move the utility to `BitwardenKit` to be shared between the apps.

**Comment by LRNcardozoWDF** [comment]
@fedemkr @matt-livefront I can't apply both your suggestions to both apps, because that introduces a lot of changes that are out of the for this task. Some of those changes break the tests leading to more changes. So I implemented it for `Authenticator.ItemListProcessor` in order to lay out some work for in the future we can reuse more code between apps.

File: AuthenticatorShared/UI/Vault/ItemList/ItemList/ItemListProcessor.swift [hunk 3]
```diff
@@ -51,20 +54,15 @@ final class ItemListProcessor: StateProcessor<ItemListState, ItemListAction, Ite
...
-            timeProvider: services.timeProvider,
-            onExpiration: { [weak self] expiredItems in
-                guard let self else { return }
-                Task {
-                    await self.refreshTOTPCodes(for: expiredItems)
-                }
-            },
-        )
+        initTOTPExpirationManagers(groupTotpExpirationManagerForTests: groupTotpExpirationManagerForTests,
+                                   searchTotpExpirationManagerForTests: searchTotpExpirationManagerForTests)
```
Comment (fedemkr) [inline AuthenticatorShared/UI/Vault/ItemList/ItemList/ItemListProcessor.swift]: ⛏️ Usually we format this on the next line for multiple parameters:
```swift
        initTOTPExpirationManagers(
            groupTotpExpirationManagerForTests: groupTotpExpirationManagerForTests,
            searchTotpExpirationManagerForTests: searchTotpExpirationManagerForTests
        )
```

File: AuthenticatorShared/UI/Vault/ItemList/ItemList/ItemListProcessor.swift [hunk 4]
```diff
@@ -154,15 +152,63 @@ final class ItemListProcessor: StateProcessor<ItemListState, ItemListAction, Ite
...
         }
     }
 
+    /// Initializes the TOTP expiration managers so the TOTP codes are refreshed automatically.
+    ///
+    private func initTOTPExpirationManagers(
+        groupTotpExpirationManagerForTests: TOTPExpirationManager? = nil,
+        searchTotpExpirationManagerForTests: TOTPExpirationManager? = nil
+    ) {
+        if let groupTotpExpirationManagerForTests, let searchTotpExpirationManagerForTests {
```
Comment (fedemkr) [inline AuthenticatorShared/UI/Vault/ItemList/ItemList/ItemListProcessor.swift]: ♻️ Add `TODO` here to refactor this on a better approach with a manager factory that can be injected and mocked by the tests without needing this specific managers being passed down the line.

Comment (LRNcardozoWDF) [reply AuthenticatorShared/UI/Vault/ItemList/ItemList/ItemListProcessor.swift]: @fedemkr I ended up implementing the factory in order to keep code coverage for the `ItemListProcessor`. The `TOTPExpirationManager` doesn't worry me as much since it's a copy from the Bitwarden app. Let me know what you think.

**Review by fedemkr — APPROVED** [review]
Looks good, I'd wait for @KatherineInCode or @matt-livefront approval as well in case I've missed anything!
♻️ Then we can tackle moving more parts to `BitwardenKit` as tech debt as you've indicated that it ends up needed a lot of other stuff to be moved there.
