### PR TITLE
PM-18244: Fix close button ui bug on ViewItem screen

### LINKED ISSUE #1344: [UI] The Close text link on the View Item panel is constantly shifting position
### Steps To Reproduce

1. Select any item.

### Expected Result

The `Close` text is static at the middle.

### Actual Result

The `Close` text appears at the top, moves to the middle, and then teleports back to the top, repeating this cycle.

### Screenshots or Videos

https://github.com/user-attachments/assets/6ef028af-40c6-4deb-8c3f-1c237f21d9b7

### Build Version

2025.1.3 (1884)

### What server are you connecting to?

US

### Environment Details

iPhone X, iOS v16.7.10.

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

### PR DESCRIPTION
**Pull request by ezimet-livefront**
## 🎟️ Tracking

[PM-18244](https://bitwarden.atlassian.net/browse/PM-18244)
## 📔 Objective

- This will fix #1344
I was able to reproduce this bug only on my old iPhone XR which runs on iOS16. 
## 📸 Screenshots

The bug was like this:
<video src=https://github.com/user-attachments/assets/6ef028af-40c6-4deb-8c3f-1c237f21d9b7 />
## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

[PM-18244]: https://bitwarden.atlassian.net/browse/PM-18244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewItemView.swift [hunk 1]
```diff
@@ -92,8 +92,10 @@ struct ViewItemView: View {
                 store.send(.editPressed)
             }
         }
-        .task {
-            await store.perform(.appeared)
+        .onAppear {
+            Task {
+                await store.perform(.appeared)
```
Comment (matt-livefront) [inline BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewItemView.swift:97]: 🤔 I don't love this pattern, since we lose out on cancellation if the view disappears before the task completes. In this case, we aren't making any network requests, so it's probably not a big deal, but I think it'd be helpful to add a comment for why we are using this pattern here and what it fixes (including affected OS versions if known).

**Comment by fedemkr** [comment]
🤔 Hi @ezimet-livefront, do you know why changing from `.task` to `.onAppear` with a closure `Task` fixes the issue? I find it really strange for the cancel button to be moving like that.

**Comment by ezimet-livefront** [comment]
> 🤔 Hi @ezimet-livefront, do you know why changing from `.task` to `.onAppear` with a closure `Task` fixes the issue? I find it really strange for the cancel button to be moving like that.

Hi @fedemkr ,
I have no idea why, but I tried lot of different things to fix this bug, I am also very confused why ```onAppear``` will work and ```task``` will broke it for iOS16, I am assuming it might be some OS related issue.

**Review by matt-livefront — APPROVED** [review]
